import {
  Baby,
  BookOpen,
  Briefcase,
  Bus,
  Car,
  CircleEllipsis,
  Clapperboard,
  Coffee,
  Dog,
  Dumbbell,
  Film,
  Fuel,
  Gamepad2,
  Gift,
  GraduationCap,
  HeartPulse,
  House,
  Landmark,
  Music,
  PiggyBank,
  Plane,
  Shirt,
  ShoppingBag,
  Smartphone,
  User,
  Utensils,
  Wallet,
  Wifi,
  Zap,
} from 'lucide-react';

export const CATEGORY_ICONS = [
  { value: 'utensils', label: 'Utensils', icon: Utensils },
  { value: 'car', label: 'Car', icon: Car },
  { value: 'house', label: 'House', icon: House },
  { value: 'zap', label: 'Zap', icon: Zap },
  { value: 'shopping-bag', label: 'Shopping bag', icon: ShoppingBag },
  { value: 'clapperboard', label: 'Clapperboard', icon: Clapperboard },
  { value: 'heart-pulse', label: 'Heart', icon: HeartPulse },
  { value: 'graduation-cap', label: 'Graduation cap', icon: GraduationCap },
  { value: 'user', label: 'User', icon: User },
  { value: 'circle-ellipsis', label: 'Other', icon: CircleEllipsis },
  { value: 'coffee', label: 'Coffee', icon: Coffee },
  { value: 'gift', label: 'Gift', icon: Gift },
  { value: 'plane', label: 'Plane', icon: Plane },
  { value: 'briefcase', label: 'Briefcase', icon: Briefcase },
  { value: 'music', label: 'Music', icon: Music },
  { value: 'book-open', label: 'Book', icon: BookOpen },
  { value: 'smartphone', label: 'Phone', icon: Smartphone },
  { value: 'wifi', label: 'Wifi', icon: Wifi },
  { value: 'shirt', label: 'Shirt', icon: Shirt },
  { value: 'landmark', label: 'Landmark', icon: Landmark },
  { value: 'dumbbell', label: 'Dumbbell', icon: Dumbbell },
  { value: 'film', label: 'Film', icon: Film },
  { value: 'gamepad-2', label: 'Game', icon: Gamepad2 },
  { value: 'piggy-bank', label: 'Savings', icon: PiggyBank },
  { value: 'baby', label: 'Baby', icon: Baby },
  { value: 'dog', label: 'Dog', icon: Dog },
  { value: 'fuel', label: 'Fuel', icon: Fuel },
  { value: 'bus', label: 'Bus', icon: Bus },
  { value: 'wallet', label: 'Wallet', icon: Wallet },
];

export const CATEGORY_COLORS = [
  '#0F766E',
  '#1D4ED8',
  '#172033',
  '#B45309',
  '#7C3AED',
  '#BE185D',
  '#15803D',
  '#0E7490',
  '#667085',
  '#44403C',
];

export function categoryIcon(name) {
  return CATEGORY_ICONS.find((item) => item.value === name)?.icon || CircleEllipsis;
}
